services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: train
      MYSQL_PASSWORD: password

volumes:
  mysql_data: